### ISSUE TITLE
32-bit support

### ISSUE THREAD

**Issue by petevine** [spacejam/rust-rocksdb#55]
How about backporting the changes from [here?](https://github.com/arkpar/rust-rocksdb/commit/bf61c18ca933850f68b730ce13d592fba6e88039)

Currently `rust-rocksdb` doesn't build on 32-bit:

```rust
src/rocksdb_options.rs:76:69: 76:73 error: mismatched types:
 expected `u32`,
    found `u64` [E0308]
src/rocksdb_options.rs:76                                                                     size);
                                                                                              ^~~~
src/rocksdb_options.rs:76:69: 76:73 help: run `rustc --explain E0308` to see a detailed explanation
src/rocksdb_options.rs:250:64: 250:68 error: mismatched types:
 expected `u64`,
    found `u32` [E0308]
src/rocksdb_options.rs:250                                                                size);
                                                                                          ^~~~
src/rocksdb_options.rs:250:64: 250:68 help: run `rustc --explain E0308` to see a detailed explanation
src/rocksdb_options.rs:76:69: 76:73 error: mismatched types:
 expected `u32`,
    found `u64` [E0308]
src/rocksdb_options.rs:76                                                                     size);
                                                                                              ^~~~
src/rocksdb_options.rs:76:69: 76:73 help: run `rustc --explain E0308` to see a detailed explanation
src/rocksdb_options.rs:250:64: 250:68 error: mismatched types:
 expected `u64`,
    found `u32` [E0308]
src/rocksdb_options.rs:250                                                                size);
                                                                                          ^~~~
src/rocksdb_options.rs:250:64: 250:68 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 2 previous errors
````

Using casts locally works OK but is not the correct cross-platform solution.

**Comment by spacejam** [comment]
https://github.com/spacejam/rust-rocksdb/pull/57 I don't have much time to try this out on an ARM toolchain, let me know if there's anything else necessary!

**Comment by spacejam** [comment]
above packaged into v0.3.3

**Comment by petevine** [comment]
I've just tested it but it made no difference. I think it's probably related to `libc 0.1`. After force-switching to `0.2` the error looks like this:

```rust
src/rocksdb_options.rs:75:69: 75:73 error: mismatched types:
 expected `usize`,
    found `u64` [E0308]
src/rocksdb_options.rs:75                                                                     size);
                                                                                              ^~~~
src/rocksdb_options.rs:75:69: 75:73 help: run `rustc --explain E0308` to see a detailed explanation
src/rocksdb_options.rs:248:64: 248:68 error: mismatched types:
 expected `u64`,
    found `usize` [E0308]
src/rocksdb_options.rs:248                                                                size);
                                                                                          ^~~~
src/rocksdb_options.rs:248:64: 248:68 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 2 previous errors
error: Could not compile `rocksdb`.
````

**Comment by petevine** [comment]
Yeah, this commit was probably necessary too:

https://github.com/arkpar/rust-rocksdb/commit/f20ac71abc573c1498f534adcfda8e22fd061533

**Comment by spacejam** [comment]
(sorry, been visiting NYC and Iceland, just moved to Berlin, chaotic journey :) I bumped the libc version, and audited the use of usize vs u64 in the ffi code and found a couple mismatches. Does that improve the situation?

**Comment by petevine** [comment]
Great, it builds fine now! Would you like to comment on this:

```shell
running 7 tests
test ffi::internal ... FAILED
test rocksdb::errors_do_stuff ... ok
test rocksdb::external ... ok
test merge_operator::mergetest ... ok
test rocksdb::iterator_test ... ok
test rocksdb::snapshot_test ... ok
test rocksdb::writebatch_works ... ok

failures:

---- ffi::internal stdout ----
        failed to open rocksdb: Invalid argument: Compression type Snappy is not linked with the binary.
thread 'ffi::internal' panicked at 'assertion failed: err.is_null()', src/ffi.rs:441
````

which probably is the reason all benchmarks are ignored in `cargo bench`. I'm using `librocksdb 4.5` built from source, so how is it possible it's missing the compression support?

**Comment by petevine** [comment]
If I'm mistaken about snappy being bundled and built with rocksdb, sorry for the fuss!

**Comment by spacejam** [comment]
Ahh yes, this is because the test is trying to use snappy compression.
Snappy is not required for rocksdb to build, however it is needed at
runtime if a db is opened with a configuration that specifies it should be
used. Maybe it uses dlopen or something at runtime, not positive off the
top of my head. I will probably have a chance to fix this in the next day
or two. Thanks for your patience with this!

**Comment by petevine** [comment]
Right, I've rebuilt `librocksdb-4.5` against `libsnappy` and the first 7 tests pass now. One from the latter batch fails however; here's the trace:

```shell
running 3 tests
test test_iterator::test_iterator ... ok
test test_column_family::test_column_family ... FAILED
test test_multithreaded::test_multithreaded ... ok

failures:

---- test_column_family::test_column_family stdout ----
        thread 'test_column_family::test_column_family' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid argument: You have to open all column families. Column families not opened: cf1"', src/libcore/result.rs:785
stack backtrace:
   1: 0xb6f3436b - std::sys::backtrace::tracing::imp::write::h82353b94d9957b5a
   2: 0xb6f37cd3 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hd08c9fd28a21a931
   3: 0xb6f3778b - std::panicking::default_hook::h9f5ce461fe95b992
   4: 0xb6f29337 - std::sys_common::unwind::begin_unwind_inner::hf3b309d035c8a630
   5: 0xb6f2a507 - std::sys_common::unwind::begin_unwind_fmt::h93bb4d1d4be19775
   6: 0xb6f33707 - rust_begin_unwind
   7: 0xb6f424df - core::panicking::panic_fmt::h5f695b461e45588f
   8: 0xb6ed2bdb - core::result::unwrap_failed::h732e927badaed544
                at src/libcore/macros.rs:29
   9: 0xb6ecfe27 - _<std..result..Result<T, E>>::unwrap::haaea95b3927d819b
                at src/libcore/result.rs:723
  10: 0xb6edc243 - test::test_column_family::test_column_family::hf87a9bf6fdc880b3
                at test/test_column_family.rs:26
  11: 0xb6ef73bf - _<F as std..boxed..FnBox<A>>::call_box::h8c9c9860460d767a
  12: 0xb6ef93bf - std::sys_common::unwind::try::try_fn::h18ba638d806a7cdc
  13: 0xb6f3369f - __rust_try
  14: 0xb6f33627 - std::sys_common::unwind::inner_try::h0ac19df8c7e3b753
  15: 0xb6ef97c7 - _<F as std..boxed..FnBox<A>>::call_box::h7b2b6b6ac924dcb2
  16: 0xb6f3610b - std::sys::thread::Thread::new::thread_start::h99197ac7442ad7fa
````

**Comment by spacejam** [comment]
This is a test that I should mark #[skip] as I think this may actually be a
limitation of librocksdb (or at least as far as I've been able to ascertain
from trying to do this with the c API from c) but I need to reconfirm and
possibly file an issue with rocksdb. This one completely boils down to
sloppiness on my part x_x

**Comment by petevine** [comment]
Cool, thanks!
